name = "f50-feedback-api"
main = "worker.js"
compatibility_date = "2026-08-21"

[vars]
GITHUB_REPO = "koldllc/f50-monitor"

# 私有反馈诊断数据存储
[[kv_namespaces]]
binding = "FEEDBACK_KV"
id = "91673f6dd50c4794b33511b5bce77b37"
